name: hutano
version: 1.0.4+5
description: A new Flutter project.
environment: 
  sdk: '>=2.6.0 <3.0.0'

dependencies: 
  fluttertoast: ^8.0.6
  http: ^0.13.3
  shared_preferences: ^2.0.5
  google_maps_flutter: ^2.0.3
  flutter_google_places: ^0.3.0
  location: ^4.1.1
  intl: ^0.17.0
  flutter_polyline_points: ^1.0.0
  flutter_rating_bar: ^4.0.0
  package_info: ^2.0.0
  image_picker: ^0.8.4
  image_cropper: ^1.3.1
  flutter_datetime_picker: ^1.5.0
  file_picker: ^4.0.1
  geocoding: ^2.0.4
  dotted_border: ^2.0.0
  map_launcher: ^2.1.1
  pedantic: ^1.8.0
  firebase_messaging: ^11.2.6
  flutter_local_notifications: ^9.3.2
  photo_view: ^0.13.0
  flutter_stripe: ^2.4.0
  flutter_svg: ^1.0.3
  url_launcher: ^6.0.3
  agora_rtc_engine: ^4.0.0-rc.3
  permission_handler: ^9.0.2
  encrypt: ^5.0.0
  flick_video_player: ^0.4.0-dev.4
  flutter_native_timezone: ^2.0.0
  country_code_picker: ^2.0.1
  uuid: ^3.0.4
  google_maps_webservice: ^0.0.20-nullsafety.2
  firebase_core: ^1.3.0
  introduction_screen: ^3.0.0
  cupertino_icons: ^1.0.3
  pin_code_fields: ^7.3.0
  flutter_custom_dialog: ^1.0.20
  flutter_typeahead: ^3.2.1
  contacts_service: ^0.6.1
  app_settings: ^4.1.1
  expandable: ^5.0.1
  infinite_scroll_pagination: ^3.0.1+1
  local_auth: ^1.1.6
  provider: ^6.0.2
  percent_indicator: ^4.0.0
  flutter_inappwebview: ^5.3.2
  connectivity: ^3.0.6
  dio: ^4.0.0
  share: ^2.0.4
  firebase_analytics: ^9.1.0
  flutter_xlider: ^3.4.0
  touchable: ^1.0.0
  keyboard_actions: ^3.4.1
  socket_io_client: ^1.0.2
  collection: ^1.15.0
  carousel_slider: ^4.0.0
  table_calendar: ^3.0.3
  fl_chart: ^0.45.0
  wakelock: ^0.5.6
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - images/
    - assets/images/
  fonts: 
    - family: Gilroy
      fonts:
        - asset: fonts/Gilroy-Light.ttf
          weight: 300
        - asset: fonts/Gilroy-Regular.ttf
          weight: 400
        - asset: fonts/Gilroy-Medium.ttf
          weight: 500
        - asset: fonts/Gilroy-SemiBold.ttf
          weight: 600
        - asset: fonts/Gilroy-Bold.ttf
          weight: 700
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
  uses-material-design: true

