name: hutano
version: 1.0.4+5
description: A new Flutter project.
environment: 
  sdk: '>=2.6.0 <3.0.0'

dependencies: 
  fluttertoast: ^8.0.6
  http: ^0.13.3
  shared_preferences: ^2.0.5
  google_maps_flutter: ^2.0.3
  flutter_google_places: ^0.3.0
  location: ^4.1.1
  intl: ^0.17.0
  flutter_polyline_points: ^1.0.0
  flutter_rating_bar: ^4.0.0
  package_info: ^2.0.0
  image_picker: ^0.7.4
  image_cropper: ^1.3.1
  flutter_datetime_picker: ^1.5.0
  file_picker: ^3.0.1
  geocoder: ^0.2.1
  dotted_border: ^2.0.0
  background_locator: ^1.3.2+1
  map_launcher: ^1.1.3+1
  pedantic: ^1.8.0
  firebase_messaging: ^9.1.3
  flutter_local_notifications: ^5.0.0+3
  photo_view: ^0.11.1
  stripe_payment: ^1.0.8
  flutter_svg: ^0.22.0
  url_launcher: ^6.0.3
  agora_rtc_engine: ^4.0.0-rc.3
  permission_handler: ^7.1.0
  encrypt: ^5.0.0
  flick_video_player: ^0.3.0
  flutter_native_timezone: ^1.0.4
  country_code_picker: ^2.0.1
  uuid: ^3.0.4
  google_maps_webservice: ^0.0.20-nullsafety.2
  firebase_core: ^1.0.2
  introduction_screen: ^1.0.9
  cupertino_icons: ^1.0.3
  pin_code_fields: ^5.1.0
  flutter_custom_dialog: ^1.0.20
  flutter_typeahead: ^3.1.3
  contacts_service: ^0.6.1
  app_settings: ^4.1.1
  expandable: ^5.0.1
  infinite_scroll_pagination: ^3.0.1+1
  local_auth: ^1.1.6
  provider: 5.0.0
  percent_indicator: ^3.0.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - images/
    - assets/images/
  fonts: 
    - family: Poppins
      fonts: 
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Medium.ttf
        - asset: fonts/Poppins-SemiBold.ttf
        - asset: fonts/Poppins-Bold.ttf
  uses-material-design: true

